# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M4zumP8uhpQDKZS9eLUXEMzYOQmlgUz

!ngrok config add-authtoken 32zh29V6cueYfAYdqC33GP86uMt_2TXXAA38rFvjSYN8iPCgb
# ---------- Single Colab Cell ----------"""


# Install required packages
!pip install streamlit pyngrok sympy -q

# Import necessary modules
import streamlit as st
from pyngrok import ngrok
import sympy as sp

# ----------------- NGROK SETUP -----------------
ngrok.kill()  # Kill any existing tunnels

# ----------------- STREAMLIT APP -----------------
app_code = r
import streamlit as st
import sympy as sp

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="All-in-One Engineering Conversion Hub",
    page_icon="馃専",
    layout="wide",
    initial_sidebar_state="expanded",
)
st.title("All-in-One Engineering Conversion Hub")
st.markdown("*Tagline:* The only Conversion hub, Engineers will ever need")

# --- UNIT SYSTEM ---
unit_system = st.sidebar.radio("Unit System", ["SI", "CGS", "USCS"])

# --- CATEGORY SELECTION ---
category = st.sidebar.selectbox("Category", ["Chemical", "Electrical"])

# --- ENGINEERING DATA WITH UNITS AND DYNAMIC FORMULAS ---
ENGINEERING_DATA = {

    "Chemical": {
        "Heat Transfer": {
            "Physical Quantities": {
                "Heat Flux": {"units": {"W/m虏": 1.0, "cal/cm虏路s": 0.0239, "Btu/ft虏路h": 0.3171}, "icon": "馃敟"},
                "Heat Transfer Rate": {"units": {"W":1.0, "cal/s":0.2388, "Btu/h":3.412}, "icon":"馃敟"},
                "Thermal Conductivity": {"units":{"W/m路K":1.0,"cal/cm路s路K":0.0002388,"Btu/ft路h路F":0.5778}, "icon":"馃尅锔?},
                "Specific Heat Capacity": {"units":{"J/kg路K":1.0,"cal/g路K":0.239,"Btu/lb路F":0.239}, "icon":"馃尅锔?},
                "Thermal Diffusivity": {"units":{"m虏/s":1.0,"cm虏/s":1e4,"ft虏/h":1.076e-4}, "icon":"馃尅锔?},
                "Temperature Gradient": {"units":{"K/m":1.0,"C/cm":100.0,"F/ft":1.8}, "icon":"馃尅锔?},
                "Convection Coefficient": {"units":{"W/m虏路K":1.0,"cal/cm虏路s路C":0.0239,"Btu/ft虏路h路F":0.3171}, "icon":"馃尅锔?},
                "Emissivity": {"units":{"-":1.0}, "icon":"馃尅锔?},
                "Area": {"units":{"m虏":1.0,"cm虏":1e4,"ft虏":10.764}, "icon":"馃搻"},
                "Mass Flow Rate": {"units":{"kg/s":1.0,"g/s":1000.0,"lb/h":7936.64}, "icon":"鈿楋笍"},
                "Latent Heat": {"units":{"kJ/kg":1.0,"cal/g":0.239,"Btu/lb":0.4299}, "icon":"馃敟"},
                "Temperature Difference": {"units":{"K":1.0,"C":1.0,"F":1.8}, "icon":"馃尅锔?}
            },
            "Laws": {
                "Fourier's Law": {"formula":"-k * A * dT_dx", "unit":"W", "variables":["k","A","dT_dx"]},
                "Newton's Law of Cooling": {"formula":"h * A * (Ts - T_inf)", "unit":"W", "variables":["h","A","Ts","T_inf"]},
                "Stefan-Boltzmann Law": {"formula":"蔚 * 蟽 * A * T**4", "unit":"W", "variables":["蔚","蟽","A","T"]},
                "Dittus-Boelter Equation": {"formula":"0.023 * Re**0.8 * Pr**0.3", "unit":"-", "variables":["Re","Pr"]},
                "LMTD": {"formula":"(deltaT1 - deltaT2)/log(deltaT1/deltaT2)", "unit":"K", "variables":["deltaT1","deltaT2"]}
            },
            "Dimensionless Numbers": {
                "Nusselt Number": {"formula":"h * L / k", "variables":["h","L","k"]},
                "Biot Number": {"formula":"h * Lc / k", "variables":["h","Lc","k"]},
                "Fourier Number": {"formula":"伪 * t / L**2", "variables":["伪","t","L"]},
                "Prandtl Number": {"formula":"谓 / 伪", "variables":["谓","伪"]},
                "Reynolds Number": {"formula":"rho * V * L / mu", "variables":["rho","V","L","mu"]},
                "Grashof Number": {"formula":"g * beta * deltaT * L**3 / nu**2", "variables":["g","beta","deltaT","L","nu"]},
                "Peclet Number": {"formula":"V * L / 伪", "variables":["V","L","伪"]},
                "Biot Number": {"formula":"h * Lc / k", "variables":["h","Lc","k"]},
                "Stefan Number": {"formula":"Cp * deltaT / L", "variables":["Cp","deltaT","L"]},
                "Sherwood Number": {"formula":"k * L / D", "variables":["k","L","D"]}
            }
        },

        "Mass Transfer": {
            "Physical Quantities": {
                "Mass Flux": {"units":{"kg/m虏路s":1.0,"g/cm虏路s":0.1,"lb/ft虏路s":0.2048},"icon":"鈿楋笍"},
                "Diffusion Coefficient": {"units":{"m虏/s":1.0,"cm虏/s":1e4,"ft虏/h":1.076e-4},"icon":"鈿楋笍"},
                "Concentration Gradient": {"units":{"kg/m鲁路m":1.0,"g/cm鲁路cm":0.001,"lb/ft鲁路ft":0.0624},"icon":"鈿楋笍"},
                "Molar Flux": {"units":{"mol/m虏路s":1.0,"mol/cm虏路s":1e-4,"mol/ft虏路h":1.076e-4},"icon":"鈿楋笍"},
                "Diffusivity Ratio": {"units":{"-":1.0},"icon":"鈿楋笍"},
                "Mass Transfer Coefficient": {"units":{"m/s":1.0,"cm/s":100.0,"ft/h":1.076},"icon":"鈿楋笍"},
                "Concentration": {"units":{"kg/m鲁":1.0,"g/cm鲁":0.001,"lb/ft鲁":0.0624},"icon":"鈿楋笍"},
                "Density": {"units":{"kg/m鲁":1.0,"g/cm鲁":0.001,"lb/ft鲁":0.0624},"icon":"鈿楋笍"},
                "Viscosity": {"units":{"Pa路s":1.0,"poise":0.1,"lb/ft路s":0.0209},"icon":"鈿楋笍"},
                "Flow Rate": {"units":{"m鲁/s":1.0,"L/s":1000.0,"ft鲁/s":35.3147},"icon":"鈿楋笍"},
                "Area": {"units":{"m虏":1.0,"cm虏":1e4,"ft虏":10.764},"icon":"馃搻"},
                "Velocity": {"units":{"m/s":1.0,"cm/s":100.0,"ft/s":3.2808},"icon":"鈿楋笍"}
            },
            "Laws": {
                "Fick's First Law": {"formula":"-D * dC_dx", "unit":"kg/m虏路s", "variables":["D","dC_dx"]},
                "Fick's Second Law": {"formula":"D * d2C_dx2", "unit":"kg/m虏路s虏", "variables":["D","d2C_dx2"]},
                "Henry's Law": {"formula":"H * xA", "unit":"Pa", "variables":["H","xA"]},
                "Darcy's Law": {"formula":"mu * L * V / K", "unit":"Pa", "variables":["mu","L","V","K"]},
                "Mass Transfer Correlation": {"formula":"Sh = k * L / D", "unit":"-", "variables":["k","L","D"]}
            },
            "Dimensionless Numbers": {
                "Sherwood Number": {"formula":"k * L / D", "variables":["k","L","D"]},
                "Schmidt Number": {"formula":"谓 / D", "variables":["谓","D"]},
                "Reynolds Number": {"formula":"rho * V * L / mu", "variables":["rho","V","L","mu"]},
                "Peclet Number": {"formula":"V * L / D", "variables":["V","L","D"]},
                "Damkohler Number": {"formula":"k * C0**n * L / V", "variables":["k","C0","n","L","V"]},
                "Biot Number": {"formula":"h * L / k", "variables":["h","L","k"]},
                "Grashof Number": {"formula":"g * beta * deltaC * L**3 / nu**2", "variables":["g","beta","deltaC","L","nu"]},
                "Fourier Number": {"formula":"D * t / L**2", "variables":["D","t","L"]},
                "Strouhal Number": {"formula":"f * L / V", "variables":["f","L","V"]},
                "Froude Number": {"formula":"V / sqrt(g*L)", "variables":["V","g","L"]}
            }
        },

        "Fluid Flow": {
            "Physical Quantities": {
                "Velocity": {"units":{"m/s":1.0,"cm/s":100.0,"ft/s":3.2808}, "icon":"馃挧"},
                "Pressure": {"units":{"Pa":1.0,"bar":1e-5,"psi":0.000145038}, "icon":"馃挧"},
                "Density": {"units":{"kg/m鲁":1.0,"g/cm鲁":0.001,"lb/ft鲁":0.0624}, "icon":"馃挧"},
                "Viscosity": {"units":{"Pa路s":1.0,"poise":0.1,"lb/ft路s":0.0209}, "icon":"馃挧"},
                "Flow Rate": {"units":{"m鲁/s":1.0,"L/s":1000.0,"ft鲁/s":35.3147}, "icon":"馃挧"},
                "Area": {"units":{"m虏":1.0,"cm虏":1e4,"ft虏":10.764}, "icon":"馃搻"},
                "Reynolds Number": {"units":{"-":1.0}, "icon":"馃挧"},
                "Mach Number": {"units":{"-":1.0}, "icon":"馃挧"},
                "Friction Factor": {"units":{"-":1.0}, "icon":"馃挧"},
                "Hydraulic Diameter": {"units":{"m":1.0,"cm":100.0,"ft":3.2808}, "icon":"馃挧"},
                "Head Loss": {"units":{"m":1.0,"ft":3.2808}, "icon":"馃挧"},
                "Flow Area": {"units":{"m虏":1.0,"cm虏":1e4,"ft虏":10.764}, "icon":"馃搻"}
            },
            "Laws": {
                "Bernoulli's Equation": {"formula":"P + 0.5 * rho * V**2 + rho * g * h", "unit":"Pa", "variables":["P","rho","V","g","h"]},
                "Darcy-Weisbach": {"formula":"f * L/D * rho * V**2 / 2", "unit":"Pa", "variables":["f","L","D","rho","V"]},
                "Continuity Equation": {"formula":"A1 * V1 = A2 * V2", "unit":"m鲁/s", "variables":["A1","V1","A2","V2"]},
                "Poiseuille's Law": {"formula":"deltaP * pi * r**4 / (8 * mu * L)", "unit":"m鲁/s", "variables":["deltaP","r","mu","L"]},
                "Friction Factor Correlation": {"formula":"(0.79 * log(Re) - 1.64)**-2", "unit":"-", "variables":["Re"]}
            },
            "Dimensionless Numbers": {
                "Reynolds Number": {"formula":"rho * V * D / mu", "variables":["rho","V","D","mu"]},
                "Froude Number": {"formula":"V / sqrt(g*L)", "variables":["V","g","L"]},
                "Mach Number": {"formula":"V / a", "variables":["V","a"]},
                "Euler Number": {"formula":"deltaP / (rho * V**2)", "variables":["deltaP","rho","V"]},
                "Strouhal Number": {"formula":"f * L / V", "variables":["f","L","V"]},
                "Prandtl Number": {"formula":"mu * Cp / k", "variables":["mu","Cp","k"]},
                "Grashof Number": {"formula":"g * beta * deltaT * L**3 / nu**2", "variables":["g","beta","deltaT","L","nu"]},
                "Nusselt Number": {"formula":"h * L / k", "variables":["h","L","k"]},
                "Biot Number": {"formula":"h * Lc / k", "variables":["h","Lc","k"]},
                "Darcy Number": {"formula":"K / L**2", "variables":["K","L"]}
            }
        }
    },

    "Electrical": {
        "Circuit": {
            "Physical Quantities": {
                "Voltage": {"units":{"V":1.0,"statV":299.7925,"V (USCS)":1.0},"icon":"鈿?},
                "Current": {"units":{"A":1.0,"abA":10.0,"A (USCS)":1.0},"icon":"鈿?},
                "Resistance": {"units":{"惟":1.0,"ab惟":1e9,"惟 (USCS)":1.0},"icon":"鈿?},
                "Capacitance": {"units":{"F":1.0,"statF":1e-9,"F (USCS)":1.0},"icon":"鈿?},
                "Inductance": {"units":{"H":1.0,"abH":1e9,"H (USCS)":1.0},"icon":"鈿?},
                "Power": {"units":{"W":1.0,"erg/s":1e7,"Btu/h":3.412},"icon":"鈿?},
                "Energy": {"units":{"J":1.0,"cal":0.239,"Btu":0.000947817},"icon":"鈿?},
                "Charge": {"units":{"C":1.0,"statC":299792458,"C (USCS)":1.0},"icon":"鈿?},
                "Flux": {"units":{"Wb":1.0,"Mx":1e8},"icon":"鈿?},
                "Magnetic Field": {"units":{"T":1.0,"G":10000},"icon":"鈿?},
                "Impedance": {"units":{"惟":1.0,"惟 (USCS)":1.0},"icon":"鈿?},
                "Frequency": {"units":{"Hz":1.0,"rpm":60},"icon":"鈿?}
            },
            "Laws": {
                "Ohm's Law": {"formula":"I * R", "unit":"V", "variables":["I","R"]},
                "Power Law": {"formula":"V * I", "unit":"W", "variables":["V","I"]},
                "Kirchhoff's Voltage Law": {"formula":"sum(V_i)", "unit":"V", "variables":["V_i"]},
                "Kirchhoff's Current Law": {"formula":"sum(I_i)", "unit":"A", "variables":["I_i"]},
                "Capacitor Energy": {"formula":"0.5 * C * V**2", "unit":"J", "variables":["C","V"]},
                "Inductor Energy": {"formula":"0.5 * L * I**2", "unit":"J", "variables":["L","I"]}
            },
            "Dimensionless Numbers": {
                "Quality Factor (Q)": {"formula":"蠅 * L / R", "variables":["蠅","L","R"]},
                "Damping Ratio (味)": {"formula":"R / (2 * (L/C)**0.5)", "variables":["R","L","C"]},
                "Power Factor": {"formula":"cos(phi)", "variables":["phi"]},
                "Skin Depth Ratio": {"formula":"delta / D", "variables":["delta","D"]},
                "Strouhal Number": {"formula":"f * L / V", "variables":["f","L","V"]},
                "Reynolds Number": {"formula":"rho * V * L / mu", "variables":["rho","V","L","mu"]}
            }
        }
    }
}

# --- SELECT SUBJECT ---
if category == "Chemical":
    section = st.sidebar.selectbox("Section", list(ENGINEERING_DATA["Chemical"].keys()))
    data = ENGINEERING_DATA["Chemical"][section]
else:
    section = st.sidebar.selectbox("Section", list(ENGINEERING_DATA["Electrical"].keys()))
    data = ENGINEERING_DATA["Electrical"][section]

# --- SELECT TYPE: PQ / Law / DN ---
selection_type = st.sidebar.radio("Select Type", ["Physical Quantity", "Law", "Dimensionless Number"])

# --- PHYSICAL QUANTITY ---
if selection_type == "Physical Quantity":
    st.subheader("Physical Quantity Conversion")
    pq = st.selectbox("Select Physical Quantity", list(data["Physical Quantities"].keys()))
    pq_data = data["Physical Quantities"][pq]
    value = st.number_input(f"Enter value of {pq}", value=0.0)
    unit_from = st.selectbox("From Unit", list(pq_data["units"].keys()))
    unit_to = st.selectbox("To Unit", list(pq_data["units"].keys()))

    converted_value = value * pq_data["units"][unit_to] / pq_data["units"][unit_from]
    st.write(f"{value} {unit_from} = {converted_value} {unit_to}")

# --- LAW CALCULATION ---
elif selection_type == "Law":
    st.subheader("Law Calculation")
    law = st.selectbox("Select Law", list(data["Laws"].keys()))
    formula_str = data["Laws"][law]["formula"]
    var_names = data["Laws"][law].get("variables", [])

    st.write(f"Formula: {formula_str}")
    if var_names:
        vars_input = st.text_input(f"Enter values for {', '.join(var_names)} separated by comma", ",".join(["1"]*len(var_names)))
        try:
            vars_list = [float(x.strip()) for x in vars_input.split(",")]
            if len(vars_list) != len(var_names):
                st.warning(f"Expected {len(var_names)} values")
            else:
                expr = sp.sympify(formula_str)
                result = expr.subs(dict(zip(var_names, vars_list)))
                st.write(f"Calculated value for {law}: {result} {data['Laws'][law]['unit']}")
        except Exception as e:
            st.error(f"Error: {e}")

# --- DIMENSIONLESS NUMBER CALCULATION ---
elif selection_type == "Dimensionless Number":
    st.subheader("Dimensionless Number Calculation")
    dn = st.selectbox("Select Dimensionless Number", list(data["Dimensionless Numbers"].keys()))
    formula_str = data["Dimensionless Numbers"][dn]["formula"]
    var_names = data["Dimensionless Numbers"][dn].get("variables", [])

    st.write(f"Formula: {formula_str}")
    if var_names:
        dn_input = st.text_input(f"Enter values for {', '.join(var_names)} separated by comma", ",".join(["1"]*len(var_names)))
        try:
            dn_vars = [float(x.strip()) for x in dn_input.split(",")]
            if len(dn_vars) != len(var_names):
                st.warning(f"Expected {len(var_names)} values")
            else:
                expr = sp.sympify(formula_str)
                dn_result = expr.subs(dict(zip(var_names, dn_vars)))
                st.write(f"Calculated value for {dn}: {dn_result}")
        except Exception as e:
            st.error(f"Error: {e}")


# Save app.py
with open("app.py", "w") as f:
    f.write(app_code)

# ----------------- NGROK TUNNEL -----------------
public_url = ngrok.connect(8501)
print("Open the Streamlit app at:", public_url)

# Start Streamlit
get_ipython().system_raw("streamlit run app.py --server.port 8501 &")
